spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI}
        registration:
          house-share-server:
            provider: keycloak
            client-id: ${SERVER_CLIENT_ID}
            client-secret: ${SERVER_CLIENT_SECRET}
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: ${SERVER_REDIRECT_URI}

          house-share-app:
            provider: keycloak
            client-id: ${APP_CLIENT_ID}
            client-secret: ${APP_CLIENT_SECRET}
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: ${APP_REDIRECT_URI}

server:
  port: ${SERVER_PORT:8080}
